### ISSUE TITLE
autodoc failure

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#269]
Ok, everything is looking good and I built files using the existing API build, which I published here: http://code.databio.org/peppy/

But for me the autodoc is still not working, so I can't re-build the API:

```
Writing API documentation for package peppy to /home/nsheff/code/peppy/docs/autodoc_build/peppy.md
All doc targets:
AttributeDict
Project
Sample
PeppyError
Processing class: AttributeDict
Processing function: add_entries
Processing function: copy
Processing function: is_null
Processing function: non_null
Processing class: Project
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/home/nsheff/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/nsheff/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/nsheff/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nsheff/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nsheff/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/nsheff/.local/lib/python2.7/site-packages/mkdocs/__main__.py", line 134, in serve_command
    livereload=livereload
  File "/home/nsheff/.local/lib/python2.7/site-packages/mkdocs/commands/serve.py", line 119, in serve
    config = builder()
  File "/home/nsheff/.local/lib/python2.7/site-packages/mkdocs/commands/serve.py", line 114, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/home/nsheff/.local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 243, in build
    config['plugins'].run_event('pre_build', config)
  File "/home/nsheff/.local/lib/python2.7/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/home/nsheff/.local/lib/python2.7/site-packages/mkdocs_plugin/plugin.py", line 111, in on_pre_build
    run_oradoc(api_pkg, self.config["docstring_style"], docs_file, self.config["no_top_level"], self.config["include_inherited"])
  File "/home/nsheff/.local/lib/python2.7/site-packages/oradocle/oradoc.py", line 367, in run_oradoc
    doc = doc_module(mod, parse, show_tag, no_mod_docstr, include_inherited)
  File "/home/nsheff/.local/lib/python2.7/site-packages/oradocle/oradoc.py", line 84, in doc_module
    output.extend(doc_class(doc_obj, docstr_parser, render_tag, include_inherited))
  File "/home/nsheff/.local/lib/python2.7/site-packages/oradocle/oradoc.py", line 119, in doc_class
    parsed_clsdoc = docstr_parser(class_docstr)
  File "/home/nsheff/.local/lib/python2.7/site-packages/oradocle/docparse.py", line 86, in __call__
    return self._last_seen if self._cached(ds) else self._parse(ds)
  File "/home/nsheff/.local/lib/python2.7/site-packages/oradocle/docparse.py", line 186, in _parse
    tags = [self._get_tag(chunk) for chunk in raw_tag_blocks]
  File "/home/nsheff/.local/lib/python2.7/site-packages/oradocle/docparse.py", line 126, in _get_tag
    tag_type, args = self._parse_tag_start(decl_line)
  File "/home/nsheff/.local/lib/python2.7/site-packages/oradocle/docparse.py", line 215, in _parse_tag_start
    raise OradocError("Invalid tag declaration start: " + line)
oradocle.exceptions.OradocError: Invalid tag declaration start: :type config_file: str
```

_Originally posted by @nsheff in https://github.com/pepkit/peppy/pull/267#issuecomment-469661212_

**Comment by vreuter** [comment]
I can't reproduce this. Did you install the `autodoc` branch of `peppy`?

**Comment by vreuter** [comment]
```
(py2) vr @ ~/code/peppy
autodoc└─ $ mkdocs serve -f mkdocs.yml 
INFO    -  Building documentation... 
Running AutoDocumenter plugin
(0, 1551797990.99801)
Writing API documentation for package peppy to docs/autodoc_build/peppy.md
All doc targets:
Project
Sample
PeppyError
fetch_samples
grab_project_data
CommandChecker
Processing class: Project
Processing function: activate_subproject
Processing function: build_sheet
Processing function: constants
Processing function: copy
Processing function: deactivate_subproject
Processing function: derived_columns
Processing function: finalize_pipelines_directory
Processing function: get_arg_string
Processing function: get_sample
Processing function: get_samples
Processing function: get_subsample
Processing function: implied_columns
Processing function: infer_name
Processing function: make_project_dirs
Processing function: num_samples
Processing function: output_dir
Processing function: parse_config_file
Processing function: project_folders
Processing function: protocols
Processing function: required_metadata
Processing function: sample_names
Processing function: samples
Processing function: set_project_permissions
Processing function: sheet
Processing function: subproject
Processing function: templates_folder
Processing class: MissingMetadataException
Processing class: MissingSampleSheetError
Processing class: Sample
Processing function: as_series
Processing function: check_valid
Processing function: copy
Processing function: determine_missing_requirements
Processing function: generate_filename
Processing function: generate_name
Processing function: get_attr_values
Processing function: get_sheet_dict
Processing function: get_subsample
Processing function: get_subsamples
Processing function: infer_attributes
Processing function: input_file_paths
Processing function: is_dormant
Processing function: library
Processing function: locate_data_source
Processing function: make_sample_dirs
Processing function: set_file_paths
Processing function: set_genome
Processing function: set_pipeline_attributes
Processing function: set_read_type
Processing function: set_transcriptome
Processing function: to_yaml
Processing function: update
Processing class: PeppyError
Processing class: CommandChecker
Processing function: failed
Processing function: fetch_samples
Processing function: grab_project_data
Writing docs: docs/autodoc_build/peppy.md
Done.
INFO    -  Cleaning site directory 
[I 190305 09:59:51 server:298] Serving on http://127.0.0.1:8000
[I 190305 09:59:51 handlers:59] Start watching changes

```

**Comment by nsheff** [comment]
> I can't reproduce this. Did you install the autodoc branch of peppy?

yes

**Comment by nsheff** [comment]
ok you're right -- I just cloned but didn't install, my bad! I keep forgetting that the autodoc requires install.
