### ISSUE TITLE
error with selector attribute

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#298]
I'm not sure why this is not working on microtest:

```
looper run config/microtest_config.yaml -d --selector-attribute "protocol" --selector-include "ATAC-seq"
Command: run (Looper version: 0.11.1)
Loading divvy config file: /nm/t1/databio/pepenv/uva_rivanna.yaml
Activating compute package 'default'
Setting sample sheet from file '/sfs/lustre/scratch/ns5bc/code/microtest/config/microtest_annotation.csv'
Ignoring nonexistent pipeline interface location: '/home/ns5bc/code//open_pipelines/pipeline_interface.yaml'
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/looper", line 10, in <module>
    sys.exit(main())
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/looper.py", line 819, in main
    run = Runner(prj)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/looper.py", line 65, in __init__
    self.counter = LooperCounter(len(prj.samples))
  File "/home/ns5bc/.local/lib/python3.6/site-packages/peppy/project.py", line 107, in __getattr__
    selector_include=self.include, selector_exclude=self.exclude)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/peppy/utils.py", line 181, in fetch_samples
    if proj.samples and not any([hasattr(i, selector_attribute) for i in proj.samples]):
  File "/home/ns5bc/.local/lib/python3.6/site-packages/peppy/utils.py", line 181, in <listcomp>
    if proj.samples and not any([hasattr(i, selector_attribute) for i in proj.samples]):
TypeError: hasattr(): attribute name must be string
```

maybe a python3 problem?

**Comment by vreuter** [comment]
My guess is that `looper` reads the inclusions/exclusions from the CLI as a list (`nargs='*'`), and then that value is being passed through the `ProjectContext` and requested as a single attribute on a `Samlpe`
