### ISSUE TITLE
AttributeError for folder_key: list object has no attribute 'items'

### ISSUE THREAD

**Issue by jpsmith5** [pepkit/peppy#312]
Peppy 0.22.dev produces AttributeError on looper call.

```
$ looper check imr90_groseq.yaml 
Command: check (Looper version: 0.12.1)
Loading divvy config file: /nm/t1/databio/divcfg/uva_rivanna.yaml
Activating compute package 'default'
Traceback (most recent call last):
  File "/home/jps3dp/.local/bin/looper", line 11, in <module>
    sys.exit(main())
  File "/home/jps3dp/.local/lib/python3.6/site-packages/looper/looper.py", line 805, in main
    file_checks=args.file_checks, compute_env_file=getattr(args, 'env', None))
  File "/home/jps3dp/.local/lib/python3.6/site-packages/looper/project.py", line 40, in __init__
    no_compute_exception=RuntimeError, **kwargs)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/peppy/project.py", line 234, in __init__
    self.make_project_dirs()
  File "/home/jps3dp/.local/lib/python3.6/site-packages/peppy/project.py", line 768, in make_project_dirs
    for folder_key, folder_val in list(self.project_folders.items()):
AttributeError: 'list' object has no attribute 'items'

```

**Comment by vreuter** [comment]
`looper` dev would need to be installed as well

**Comment by jpsmith5** [comment]
Also resolved with looper dev. Closing for now.
