### ISSUE TITLE
in validator, should '*' validate for anything?

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#340]
I have a sample file where protocol is '*':

```
peppy validate paqc.yaml -s http://schema.databio.org/pipelines/pepatac.yaml
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/peppy", line 10, in <module>
    sys.exit(main())
  File "/home/ns5bc/.local/lib/python3.6/site-packages/peppy/cli.py", line 85, in main
    p.validate_project(args.schema, args.exclude_case)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/peppy/project.py", line 760, in validate_project
    exclude_case)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/peppy/project.py", line 828, in _validate_object
    jsonschema.validate(object, schema)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: '*' is not one of ['ATAC', 'ATAC-SEQ', 'ATAC-seq', 'DNase', 'DNase-seq']

Failed validating 'enum' in schema['properties']['_samples']['items']['properties']['protocol']:
    {'description': 'Must be an ATAC-seq or DNAse-seq sample',
     'enum': ['ATAC', 'ATAC-SEQ', 'ATAC-seq', 'DNase', 'DNase-seq'],
     'type': 'string'}

On instance['_samples'][0]['protocol']:
    '*'
```

**Comment by stolarczyk** [comment]
do you suggest to tweak the validator in peppy? Can this be solved by adding `*` to enum in the schema?

**Comment by nsheff** [comment]
Actually my thinking was inverted. This doesn't make sense. Nevermind.
