### ISSUE TITLE
Duplicated error message upon project load

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#483]
Using the example pep in the [dnameth pipeline](https://github.com/databio/dnameth_pipelines), I see:

```
looper check
No project config defined (peppy), using: {'config_file': 'test_config.yaml', 'output_dir': '.', 'sample_pipeline_interfaces': None, 'project_pipeline_interfaces': None}. Read from dotfile (/home/nsheff/code/dnameth_pipelines/examples/.looper.yaml).
Config file does not have version key. Defaulting to 2.1.0
Looper version: 1.5.2-dev
Command: check
Config file does not have version key. Defaulting to 2.1.0
Not all environment variables were populated in derived attribute source: $CODE/microtest/data/{filename}
Not all environment variables were populated in derived attribute source: $CODE/microtest/data/{filename}
Not all environment variables were populated in derived attribute source: $CODE/microtest/data/{filename}
Not all environment variables were populated in derived attribute source: $CODE/microtest/data/{filename}
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/looper", line 8, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/looper.py", line 1125, in main
    p = Project(
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/project.py", line 118, in __init__
    setattr(self[EXTRA_KEY], attr_name, kwargs[attr_name])
  File "/home/nsheff/.local/lib/python3.8/site-packages/peppy/project.py", line 1365, in __getitem__
    return self._project_data[item]
KeyError: '_cli_extra'
```

Why does it say: `Config file does not have version key. Defaulting to 2.1.0` two times?

 is looper loading the PEP twice?

**Comment by saanikat** [comment]
After discussion, it was discovered that this issue lies in peppy.

**Comment by khoroshevskyi** [comment]
This issue should be solved together with #465
